test ci

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -121,3 +121,51 @@ jobs:
       - name: Push Backend image
         if: needs.changes.outputs.backend == 'true'
         run: docker push ${{ env.BACKEND_IMAGE }}:${{ steps.sha.outputs.sha }}
+
+  update-helm-chart:
+    needs: deploy
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Helm chart repository from GitLab
+        run: |
+          git clone https://github-actions:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.2rocksstudio.hk/devops/dg-argocd.git
+
+      - name: Install yq
+        run: |
+          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
+          sudo chmod +x /usr/bin/yq
+
+      - name: Set branch name
+        id: set-branch
+        run: |
+          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
+            echo "::set-output name=branch::main"
+          elif [[ ${{ github.ref }} == 'refs/heads/uat' ]]; then
+            echo "::set-output name=branch::uat"
+          elif [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
+            echo "::set-output name=branch::dev"
+          else
+            echo "::error ::Invalid branch name"
+            exit 1
+          fi
+
+      - name: Update Backend Helm chart image.tag value
+        if: needs.changes.outputs.backend == 'true'
+        run: |
+          cd dg-argocd/app-center/backend-helm
+          yq eval '.image.tag = "${{ needs.deploy.outputs.sha }}"' -i values.${{ steps.set-branch.outputs.branch }}.yaml
+
+      - name: Update Frontend Helm chart image.tag value
+        if: needs.changes.outputs.frontend == 'true'
+        run: |
+          cd dg-argocd/app-center/portal-helm
+          yq eval '.image.tag = "${{ needs.deploy.outputs.sha }}"' -i values.${{ steps.set-branch.outputs.branch }}.yaml
+
+      - name: Commit and push changes to Helm chart repository
+        run: |
+          cd ../../../
+          git config --global user.email "github-actions@2rocksstudio.hk"
+          git config --global user.name "GitHub Actions"
+          git add .
+          git commit -m "Update image.tag to ${{ needs.deploy.outputs.sha }} for ${{ steps.set-branch.outputs.branch }} branch"
+          git push origin main
